name: TropiCam-AI
channels:
  - conda-forge
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - brotli=1.1.0=hcfcfb64_1
  - brotli-bin=1.1.0=hcfcfb64_1
  - brotli-python=1.1.0=py39h99910a6_1
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2024.8.30=h56e8100_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py39ha55e580_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.1=py39h1f6ef14_0
  - cudatoolkit=11.2.2=h7d7167e_13
  - cudnn=8.1.0.77=h3e0f4f4_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.5=py39ha51f57c_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - fonttools=4.53.1=py39ha55e580_0
  - freetype=2.12.1=hdaf720e_2
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.8=pyhd8ed1ab_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib-resources=6.4.4=pyhd8ed1ab_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - importlib_resources=6.4.4=pyhd8ed1ab_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.18.1=pyh7428d3b_3
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hcbf5309_0
  - kiwisolver=1.4.5=py39h2b77a98_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=23_win64_mkl
  - libbrotlicommon=1.1.0=hcfcfb64_1
  - libbrotlidec=1.1.0=hcfcfb64_1
  - libbrotlienc=1.1.0=hcfcfb64_1
  - libcblas=3.9.0=23_win64_mkl
  - libdeflate=1.21=h2466b09_0
  - libffi=3.4.2=h8ffe710_5
  - libhwloc=2.11.1=default_h8125262_1000
  - libiconv=1.17=hcfcfb64_2
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=23_win64_mkl
  - libpng=1.6.43=h19919ed_0
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.46.0=h2466b09_0
  - libtiff=4.6.0=hb151862_4
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.12.7=h0f24e4e_4
  - libzlib=1.3.1=h2466b09_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-base=3.8.4=py39he1095e7_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2024.1.0=h66d3029_694
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openjpeg=2.5.2=h3d672ee_0
  - openssl=3.3.1=h2466b09_3
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=1.3.3=py39h2e25243_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py39hfa8c767_0
  - pip=24.2=pyhd8ed1ab_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py39ha55e580_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.9.19=h4de0772_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.9=5_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=306=py39h99910a6_2
  - pyzmq=26.2.0=py39h03e5c00_0
  - requests=2.32.3=pyhd8ed1ab_0
  - scikit-learn=1.5.1=py39hdd013cc_0
  - scipy=1.11.2=py39hde5eda1_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=59.8.0=py39hcbf5309_1
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py39hbaa61f9_1
  - tbb=2021.12.0=hc790b64_4
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h5226925_1
  - tornado=6.4.1=py39ha55e580_1
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h8827d51_1
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.1.0=py39ha55989b_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - vc=14.3=h8a93ad2_20
  - vc14_runtime=14.40.33810=hcc2c482_20
  - vs2015_runtime=14.40.33810=h3bf8584_20
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - zeromq=4.3.5=he1f189c_4
  - zipp=3.20.1=pyhd8ed1ab_0
  - zstandard=0.23.0=py39h9bf74da_0
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.5.0
      - flatbuffers==24.3.25
      - gast==0.4.0
      - google-auth==2.34.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.66.0
      - h5py==3.11.0
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==18.1.1
      - markdown==3.7
      - markupsafe==2.1.5
      - numpy==1.24.0
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==3.19.6
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - werkzeug==3.0.4
      - wrapt==1.16.0